/**
 * The provenance markers the dedicated VIP/PREMIUM pass stamps on the picks it
 * promotes. See VIP_GENERATED_PROVENANCE's note in src/lib/geniusCuration.ts for
 * why there are two. No runtime imports, on purpose: pure modules (the Goals pass, the
 * curation planner) need these without loading Prisma.
 */
import type { Prisma } from "@prisma/client";

export const VIP_GENERATED_PROVENANCE = "VIP_GENERATED" as const;
export const PREMIUM_GENERATED_PROVENANCE = "PREMIUM_GENERATED" as const;

/**
 * Provenances whose rows are PAID-ONLY picks: generated by the dedicated
 * VIP/PREMIUM pass for that purpose, as a different selection from every other
 * pick on the fixture (see repeatsExistingPick in vipPremiumOverlay.ts).
 *
 * Such a row belongs to VIP/PREMIUM alone. It is never shown in, curated into
 * or derived into another feed — not Today, Genius, Goals, Featured or the
 * accumulators — so a paid pick is never also a free one, and it never takes a
 * slot from another category's pick. MARKET_CONFIRMED is NOT here: its three
 * rows were ordinary picks tagged afterwards, and they keep their history.
 */
export const PAID_ONLY_PROVENANCES = [VIP_GENERATED_PROVENANCE, PREMIUM_GENERATED_PROVENANCE] as const;

export function isPaidOnlyProvenance(provenance: string | null | undefined): boolean {
  return (PAID_ONLY_PROVENANCES as readonly string[]).includes(provenance ?? "");
}

/** Prisma filter: rows that are NOT paid-only. provenance is non-null (default STANDARD_CURATED), so notIn keeps every other row. */
export const NOT_PAID_ONLY: Prisma.PredictionWhereInput = { provenance: { notIn: [...PAID_ONLY_PROVENANCES] } };
