import { PolicyCallout, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Responsible Gambling", "Practical guidance for safer gambling, recognising harm, setting limits, taking breaks and finding support.", "/responsible-gambling");

export default function ResponsibleGamblingPage() {
  return <TrustPage eyebrow="18+ · Safer play" title="Responsible gambling" intro={<p>Gambling should be optional entertainment paid for from disposable money. It is not a way to recover debt, replace income or guarantee profit.</p>} sections={[
    { id: "limits", title: "Set boundaries before you bet", content: <ul><li>Choose a loss limit you can comfortably afford and do not increase it after play begins.</li><li>Set deposit, stake and time limits using your betting operator’s tools.</li><li>Keep gambling money separate from rent, food, school fees, transport, savings and debt payments.</li><li>Track total deposits and withdrawals—not only individual wins.</li><li>Take regular breaks and avoid gambling when distressed, angry, tired or affected by alcohol or drugs.</li></ul> },
    { id: "never-chase", title: "Do not chase losses", content: <><PolicyCallout tone="warning">A loss does not make the next bet more likely to win. Increasing stakes to “win it back” can turn a manageable loss into serious harm.</PolicyCallout><p>Do not borrow, sell essential belongings or use credit to gamble. Stop when the planned limit is reached, regardless of recent results.</p></> },
    { id: "warning-signs", title: "Recognise warning signs", content: <ul><li>Spending more money or time than intended.</li><li>Hiding gambling activity or lying about losses.</li><li>Borrowing, missing bills or using essential funds.</li><li>Feeling restless, anxious or irritable when trying to stop.</li><li>Gambling to escape stress, or repeatedly trying to recover losses.</li><li>Damage to work, study, health or relationships.</li></ul> },
    { id: "take-action", title: "If gambling is causing harm", content: <ol><li>Stop betting and tell someone you trust.</li><li>Use the operator’s deposit limits, time-outs and self-exclusion tools.</li><li>Remove gambling apps, promotional messages and saved payment methods.</li><li>Ask your bank or payment provider whether gambling-payment controls are available.</li><li>Contact a licensed gambling-support service or a qualified local healthcare professional.</li></ol> },
    { id: "resources", title: "Finding support", content: <p>BetGenius does not publish unverified helplines or organisations. For support in Nigeria or elsewhere, use a licensed betting operator’s responsible-gambling and self-exclusion channels, contact a qualified healthcare professional, or consult a recognised gambling-support service available in your jurisdiction. If you or someone else is in immediate danger, contact local emergency services.</p> },
    { id: "minors", title: "Protecting minors", content: <p>BetGenius content and betting services are for people aged 18 or older. Adults should keep account credentials and payment methods secure, avoid leaving betting sessions open on shared devices, and use device or network controls where appropriate.</p> },
  ]} />;
}
