import { PolicyCallout, TrustLink, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Terms of Use", "Terms governing access to BetGenius football predictions, accounts, subscriptions and third-party links.", "/terms");
const date = "28 August 2026";

export default function TermsPage() {
  return <TrustPage eyebrow="Legal" title="Terms of use" effectiveDate={date} intro={<p>These terms govern access to BetGenius.ng. By using the service, you agree to them. If you do not agree, do not use the site.</p>} sections={[
    { id: "eligibility", title: "Eligibility and lawful use", content: <p>You must be at least 18 and legally able to use this service. You are responsible for complying with laws and betting restrictions in your location. Do not use BetGenius to facilitate unlawful conduct, interfere with security, impersonate others or abuse the service.</p> },
    { id: "service", title: "Nature of the service", content: <><p>BetGenius provides football predictions, statistics, match previews and analytical opinions. It is not a bookmaker and does not guarantee an outcome or profit.</p><PolicyCallout tone="warning">Betting involves financial risk. Read the <TrustLink href="/betting-disclaimer">Betting Disclaimer</TrustLink> before relying on any prediction.</PolicyCallout></> },
    { id: "accounts", title: "Accounts", content: <p>Provide accurate information, keep credentials secure and tell us promptly about suspected unauthorised access. You are responsible for activity through your account unless law provides otherwise. We may restrict an account to protect users, investigate misuse or enforce these terms.</p> },
    { id: "subscriptions", title: "Subscriptions and payments", content: <p>Paid tiers provide access to the features described at checkout for the stated billing period. Prices and currency are shown before payment and verified server-side. Payments are processed through Paystack and may also be subject to Paystack’s terms. Unless mandatory consumer law says otherwise, completed access periods are not automatically refundable merely because predictions lose or because you did not use the service. Any specific cancellation or refund terms shown at checkout also apply.</p> },
    { id: "responsibility", title: "Your responsibility", content: <p>You decide whether to act on information and should independently verify time-sensitive facts. Do not stake money you cannot afford to lose. BetGenius content is not financial advice and should not be treated as income or an investment strategy.</p> },
    { id: "ip", title: "Intellectual property and permitted use", content: <p>Site design, original writing, analysis and compilations are owned by BetGenius or their respective licensors. You may use the site personally and lawfully. You may not systematically scrape, copy, republish, sell, frame or create a competing database from the service without written permission. Fair quotation and links remain subject to applicable law.</p> },
    { id: "third-parties", title: "Third-party services and affiliate links", content: <p>Links may lead to bookmakers or other services we do not control. Their terms, eligibility, odds, promotions and privacy practices apply. Some links may generate commission; see the <TrustLink href="/affiliate-disclosure">Affiliate Disclosure</TrustLink>. A link is not a guarantee of availability, legality or outcome.</p> },
    { id: "accuracy-availability", title: "Accuracy and availability", content: <p>We aim for useful, timely content, but data feeds, statistics, schedules and analysis may contain delays or errors. The service may be interrupted for maintenance, provider failures or events outside reasonable control. We do not promise uninterrupted availability.</p> },
    { id: "liability", title: "Liability", content: <p>To the fullest extent permitted by law, the operator of BetGenius.ng is not liable for indirect or consequential loss, betting losses, lost profit or decisions made from site content. Nothing here excludes liability that cannot legally be excluded, including liability arising from fraud or other non-excludable duties.</p> },
    { id: "indemnity", title: "Responsibility for misuse", content: <p>You are responsible for reasonable losses or claims caused by your unlawful use, infringement of another person’s rights or material breach of these terms. This does not apply beyond what is fair or permitted by law.</p> },
    { id: "termination", title: "Suspension and termination", content: <p>We may suspend or end access where reasonably necessary for security, non-payment, unlawful activity, abuse or serious breach. Where practical, we will consider notice and an opportunity to resolve the issue. You may stop using the service at any time.</p> },
    { id: "law-changes", title: "Governing law, changes and contact", content: <p>These terms are governed by the laws of the Federal Republic of Nigeria, without removing mandatory protections that apply to users elsewhere. Disputes should first be raised through the <TrustLink href="/contact">Contact page</TrustLink>. We may update these terms prospectively; the updated date will be shown above.</p> },
  ]} />;
}
