import { TrustLink, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Privacy Policy", "How BetGenius collects, uses, shares and protects account, subscription, device and enquiry data.", "/privacy-policy");
const date = "28 August 2026";

export default function PrivacyPolicyPage() {
  return <TrustPage eyebrow="Legal" title="Privacy policy" effectiveDate={date} intro={<p>This policy explains how BetGenius.ng handles personal information when you browse the site, create an account, subscribe or communicate with us. It applies to visitors in Nigeria and elsewhere, subject to local law.</p>} sections={[
    { id: "information", title: "Information we collect", content: <><p><strong>Account information:</strong> name, email address, authentication details and account role. Passwords are stored as protected hashes, not readable text. If you sign in with Google, we receive account identifiers and profile information made available through that sign-in.</p><p><strong>Subscription information:</strong> selected tier, subscription status, payment reference, billing period and Paystack customer or subscription identifiers. BetGenius does not need to store your full payment-card number.</p><p><strong>Technical information:</strong> hosting and security systems may process IP address, browser, device, request time, referring page, logs and error data. If you contact us, we process the information included in the enquiry.</p></> },
    { id: "use", title: "How we use information", content: <ul><li>Provide accounts, gated predictions and subscription access.</li><li>Authenticate users, prevent abuse and protect the service.</li><li>Initialize and verify payments and respond to account enquiries.</li><li>Operate, diagnose and improve site reliability and content.</li><li>Meet legal obligations and enforce our terms.</li><li>Measure advertising or affiliate performance where those technologies are introduced and lawfully enabled.</li></ul> },
    { id: "legal-bases", title: "Why we process it", content: <p>Depending on the context and applicable law, processing may be necessary to perform a contract with you, comply with law, pursue legitimate interests such as security and service improvement, or act on consent. Where consent is required, it may be withdrawn for future processing.</p> },
    { id: "cookies-ads", title: "Cookies, analytics and advertising", content: <><p>Essential cookies support login sessions, security and preferences such as theme. See the <TrustLink href="/cookie-policy">Cookie Policy</TrustLink> for details.</p><p>The current codebase does not include a Google Analytics or Google AdSense tag or a consent-management platform. If analytics or advertising is added, this policy and the cookie controls must be updated before use. Advertising partners such as Google may then use cookies or similar identifiers to deliver, limit, personalise where permitted, and measure advertising. Consent will be requested where law requires it.</p></> },
    { id: "sharing", title: "Service providers and third parties", content: <p>Information may be processed by providers needed to run the service, including hosting and database providers, authentication services, Paystack for payments and football-data providers. Affiliate partners may receive click or transaction attribution when you follow a commercial link. Each provider handles data under its own terms and privacy obligations.</p> },
    { id: "international", title: "International processing", content: <p>Some providers may process information outside Nigeria or your country. Where required, we rely on contractual safeguards or other lawful transfer mechanisms. The protections available can differ by jurisdiction.</p> },
    { id: "retention", title: "Retention", content: <p>We retain information only for as long as reasonably needed for the purpose collected, including account operation, transaction records, security, dispute resolution and legal obligations. Retention periods vary by record type. Data may remain in backups for a limited recovery period after deletion from active systems.</p> },
    { id: "rights", title: "Your choices and rights", content: <p>Subject to applicable law, you may request access, correction, deletion, restriction, objection or portability of personal information, or withdraw consent. You may also complain to the relevant data-protection authority. We may verify identity and may retain information where law or legitimate claims require it. Use the verified channel on our <TrustLink href="/contact">Contact page</TrustLink>.</p> },
    { id: "security", title: "Security", content: <p>We use technical and organisational safeguards appropriate to the service, including protected credentials, access controls and server-side payment verification. No internet system is completely secure. Protect your password and contact us if you suspect unauthorised access.</p> },
    { id: "children", title: "Children’s privacy", content: <p>BetGenius is intended for adults aged 18 or older. We do not knowingly seek personal information from children. If you believe a child has provided account information, contact us so it can be investigated and removed where appropriate.</p> },
    { id: "changes", title: "Changes and contact", content: <p>We may update this policy when the service, providers or law changes. The revised date will appear above. Material changes may also be highlighted on the site. Privacy questions and rights requests should be sent through the <TrustLink href="/contact">Contact page</TrustLink>.</p> },
  ]} />;
}
