import { TrustLink, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Prediction Methodology", "How BetGenius combines football data and evidence thresholds to produce transparent predictions.", "/methodology");

export default function MethodologyPage() {
  return <TrustPage eyebrow="Transparency" title="How BetGenius predictions are produced" intro={<p>Our process starts with football evidence. Structured data is gathered and checked, then the available signals are assessed to produce a readable prediction and explanation.</p>} sections={[
    { id: "evidence", title: "Evidence we assess", content: <><p>Coverage varies by fixture, but the system can assess season records, recent form, home and away performance, goals scored and conceded, clean-sheet and scoring trends, standings, head-to-head meetings, fixture and competition context, team news, injuries and suspensions.</p><p>Venue-specific evidence matters: a home side’s home record is compared with an away side’s away record where enough matches exist. Short samples and unavailable data are not treated as if they were complete evidence.</p></> },
    { id: "quality", title: "Data quality and evidence thresholds", content: <p>Our match pages score the presence of substantive evidence. Team records, recent form and usable statistical splits carry more weight than a single supporting detail. Head-to-head, standings, current team news and a published analysis can strengthen the picture. Pages with too little evidence should not be presented as equally informative to well-supported fixtures.</p> },
    { id: "markets", title: "Market and confidence selection", content: <p>The recommended market should fit the evidence pattern rather than default to one generic “safe” option. Confidence expresses the strength of the assessment on the platform’s scale; it is not the actual probability of winning, a quoted bookmaker price or a guarantee. Multi-condition picks use compatibility rules, show the lower leg confidence, and do not fabricate a joint probability.</p> },
    { id: "read", title: "How to read a prediction", content: <ul><li><strong>Prediction or pick:</strong> the outcome the analysis favours.</li><li><strong>Recommended market:</strong> the type of bet to which the pick applies.</li><li><strong>Confidence:</strong> a comparative assessment of evidential strength, not certainty.</li><li><strong>Reasoning:</strong> the main evidence supporting the choice and, where available, relevant counter-risk.</li><li><strong>Risk:</strong> the possibility that missing information, match events or ordinary variance defeats the assessment.</li></ul> },
    { id: "odds", title: "Market odds and extra checks", content: <p>Where real odds coverage is available, certain products may compare the internal confidence assessment with market-implied probability. This is an additional check, not proof. Odds move, include bookmaker margin and can be unavailable or stale; their presence never converts a prediction into a certainty.</p> },
    { id: "limits", title: "What the process cannot know", content: <p>Late line-up changes, new injuries, tactical surprises, weather, referee decisions, red cards, data-provider delays and random events can invalidate a sound pre-match assessment. We settle published predictions against results and use the record to evaluate performance, but past performance does not guarantee future results.</p> },
    { id: "standards", title: "Review, corrections and responsibility", content: <p>Predictions enter a review workflow before publication. Our <TrustLink href="/editorial-policy">Editorial Policy</TrustLink> explains sourcing, corrections, publication standards and commercial independence. Before betting, read the <TrustLink href="/betting-disclaimer">Betting Disclaimer</TrustLink>.</p> },
  ]} />;
}
