import Link from "next/link";
import type { Metadata } from "next";
import { JsonLd, breadcrumbJsonLd, SITE_NAME } from "@/lib/seo";

/**
 * The site's standing disclosure of how predictions are produced.
 *
 * This page exists because the AI branding was deliberately pulled out of the
 * homepage hero, the navigation and the meta descriptions (see the note on the
 * hero in src/app/(public)/page.tsx). Quieting the marketing claim is only
 * honest if the fact itself stays easy to find, so the disclosure moved here
 * and into the footer of every page rather than disappearing.
 *
 * Deliberately plain and specific. A vague "we use advanced technology" line
 * would be worse than the headline it replaced; what a reader needs is which
 * part is generated, which part is measured data, who reviews it, and what the
 * limits are.
 */
export const metadata: Metadata = {
  title: "How our predictions are made",
  description:
    "How BetGenius produces its football predictions: the match data behind every pick, the AI-generated analysis, the human review before publication, and the published settled-results record.",
  alternates: { canonical: "/methodology" },
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-gray-300">{children}</div>
    </section>
  );
}

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <JsonLd
        data={breadcrumbJsonLd([
          { name: "Home", path: "/" },
          { name: "How our predictions are made", path: "/methodology" },
        ])}
      />

      <header className="space-y-3">
        <h1 className="text-2xl font-bold">How our predictions are made</h1>
        <p className="text-sm leading-relaxed text-gray-300">
          Every prediction on {SITE_NAME} is generated by an AI model working from live match data, and reviewed by
          a human before it is published. Nothing is posted automatically without that review. This page explains what
          that means in practice, including where it can go wrong.
        </p>
      </header>

      <Section title="The data behind a pick">
        <p>
          Before a prediction is written, we pull the match&apos;s real record from API-Football: both teams&apos; recent
          results and scoring rates, their league position and points, home and away splits, current injuries and
          suspensions, and the head-to-head history between the two sides.
        </p>
        <p>
          The figures shown on a match page are read from that same cached data — not from the model. If a number
          appears on the page, it came from the data feed, so the model and the reader are working from one set of
          numbers rather than two.
        </p>
      </Section>

      <Section title="What the AI writes">
        <p>
          The model receives that data and returns the call itself: the market, the selection, a confidence rating,
          the key factors, and the written reasoning and match preview. Those written sections are AI-generated
          text. The confidence percentage is the model&apos;s own estimate of how likely its call is — it is not a
          measured probability and not a guarantee.
        </p>
      </Section>

      <Section title="The human review">
        <p>
          Generated predictions land as drafts. An editor reads each one and either publishes it, sends it back to be
          rewritten, or discards it. Publication and any later settlement are recorded against the account that
          performed them, so every published pick has a named reviewer behind it.
        </p>
      </Section>

      <Section title="How picks are ranked">
        <p>
          Which picks are featured, and the order they appear in across the site, follow one rule: competition
          priority first — the major leagues and cups ahead of smaller ones — then confidence, highest first. The
          same ranking decides which tips are promoted into the Genius, VIP and Premium feeds.
        </p>
      </Section>

      <Section title="Where this can be wrong">
        <p>
          AI-generated analysis can be confidently wrong. It can misread a thin data set, lean on a stale injury
          list, or produce reasoning that sounds firmer than the evidence supports. Coverage is also uneven: smaller
          competitions carry less data than the top leagues, and a pick made on less data is a weaker pick regardless
          of the confidence number attached to it.
        </p>
        <p>
          This is why we publish results. Every settled pick — won, lost or void — is counted on the{" "}
          <Link href="/track-record" className="text-brand hover:underline">
            track record
          </Link>{" "}
          page, including the losing ones.
        </p>
      </Section>

      <Section title="Please bet responsibly">
        <p>
          Predictions are opinion and information, not financial advice. {SITE_NAME} does not take bets or handle
          funds. Betting is for over-18s only; never stake more than you can afford to lose.
        </p>
      </Section>
    </div>
  );
}
