import { PolicyCallout, TrustLink, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Cookie Policy", "Learn which cookies BetGenius uses now and how analytics, advertising and affiliate cookies would be handled.", "/cookie-policy");
const date = "10 October 2026";

export default function CookiePolicyPage() {
  return <TrustPage eyebrow="Legal" title="Cookie policy" effectiveDate={date} intro={<p>Cookies are small text files stored by a browser. Similar technologies can store identifiers or measure how a service is used. This policy distinguishes what BetGenius uses now from technologies that may be introduced later.</p>} sections={[
    { id: "essential", title: "Essential cookies", content: <p>BetGenius uses cookies or browser storage needed for authentication sessions, account security and basic product operation. These technologies cannot always be disabled through the site without breaking login or other requested features.</p> },
    { id: "preferences", title: "Preferences and functionality", content: <p>The site stores your light, dark or system theme choice on your device so the interface can remember it. Other functional preferences may be added when needed and documented here.</p> },
    { id: "analytics", title: "Analytics cookies", content: <p>BetGenius uses Google Analytics 4 to measure how pages are used and how the site performs. It stores cookies or similar identifiers on your device and sends measurement data, including a device identifier and the pages you view, to Google. It is not required for the site to work, so it sets no cookies until you accept them in the cookie banner. Until then, Google receives only basic, cookieless signals that a page was viewed — see <TrustLink href="#controls">Managing cookies</TrustLink>.</p> },
    { id: "advertising", title: "Advertising cookies", content: <><p>BetGenius shows advertising supplied by a third-party network, Adsterra. Ad units load inside a sandboxed frame served from a separate hostname, ads.betgenius.ng, and the network may store cookies or similar identifiers — including on the betgenius.ng domain — to serve, limit, measure and, where permitted, personalise ads. BetGenius does not control what those identifiers contain or how long they last. The application does not include a Google AdSense tag.</p><p>BetGenius also uses the Meta Pixel to measure the results of its own adverts on Facebook and Instagram. It sets cookies or similar identifiers on your device and sends Meta the pages you visit, along with browser and device information, so visits can be linked to those adverts and used to build advertising audiences. The Meta Pixel sends nothing and sets no cookies until you accept them in the cookie banner.</p><PolicyCallout>BetGenius does not claim AdSense approval or Google endorsement. This policy describes how advertising technology will be handled if it is enabled.</PolicyCallout></> },
    { id: "affiliate", title: "Affiliate and third-party cookies", content: <p>When you follow a bookmaker or other affiliate link, the third party may set a cookie or record an identifier to attribute a registration or transaction. BetGenius does not control those third-party cookies. Review the destination site’s policy and our <TrustLink href="/affiliate-disclosure">Affiliate Disclosure</TrustLink>.</p> },
    { id: "controls", title: "Managing cookies", content: <><p>You can block or delete cookies in your browser settings. Doing so may sign you out, reset preferences or prevent parts of the site from working.</p><p>On your first visit, a banner asks whether you accept analytics and advertising-measurement cookies (Google Analytics and the Meta Pixel). Rejecting is as easy as accepting, and the site works the same either way. You can change your answer at any time from the Cookie settings link in the footer. Your choice is stored on your device, so clearing site data means you will be asked again.</p><p>The banner does not control cookies set by the Adsterra ad network inside its separate ad frame, or by affiliate sites you visit. For those, use your browser settings.</p></> },
    { id: "changes", title: "Updates and questions", content: <p>We will update this policy when our use of cookies changes. For privacy questions, read the <TrustLink href="/privacy-policy">Privacy Policy</TrustLink> or use the verified channel on the <TrustLink href="/contact">Contact page</TrustLink>.</p> },
  ]} />;
}
