import crypto from "crypto";
import type { PaidTier } from "@/lib/pricing";

/**
 * The checkout reference encodes the tier being bought.
 *
 * WHY. Starting a checkout used to overwrite the subscription row with
 * `{ tier: <the tier being bought>, status: "PENDING" }`. For an existing
 * subscriber that revoked the access they had already paid for the moment they
 * clicked — before paying, and for good if they abandoned the page. Leaving the
 * row alone instead means the row no longer records which tier is in flight,
 * and the webhook needs that to know what to grant.
 *
 * Rather than add a column for it, the tier rides in the reference we hand
 * Paystack. That keeps the tier bound to something Paystack echoes back and the
 * webhook already verifies independently (REFERENCE_MISMATCH), so
 * `validateVerifiedEntitlement`'s tier cross-check stays a real check against
 * the transaction's metadata rather than a comparison of the payload with
 * itself.
 *
 * The random half is what makes a reference single-use; Paystack rejects a
 * duplicate reference outright.
 */
const PATTERN = /^bg_(VIP|PREMIUM)_[0-9a-f]{32}$/;

export function newCheckoutReference(tier: PaidTier): string {
  return `bg_${tier}_${crypto.randomBytes(16).toString("hex")}`;
}

/**
 * The tier a reference was created for, or null when it is not one of ours.
 *
 * Null is the legacy case, not an error: references created before this shipped
 * were generated by Paystack and carry no tier, so the caller falls back to the
 * tier stored on the row — which is what those in-flight checkouts recorded.
 */
export function tierFromCheckoutReference(reference: string | null | undefined): PaidTier | null {
  if (!reference || !PATTERN.test(reference)) return null;
  return reference.split("_")[1] as PaidTier;
}
