import { PolicyCallout, TrustLink, TrustPage } from "@/components/trust/TrustPage";
import { trustMetadata } from "@/lib/trustMetadata";

export const metadata = trustMetadata("Editorial Policy", "BetGenius standards for football data, prediction quality, corrections and commercial independence.", "/editorial-policy");
const date = "28 August 2026";

export default function EditorialPolicyPage() {
  return <TrustPage eyebrow="Editorial standards" title="Editorial policy" effectiveDate={date} intro={<p>This policy describes how BetGenius aims to keep football predictions and match information useful, evidence-based, transparent and separate from commercial influence.</p>} sections={[
    { id: "independence", title: "Editorial independence", content: <p>Prediction conclusions should follow the match evidence. Advertising, affiliate commissions, subscription status and relationships with betting operators must not determine a pick, market or confidence assessment. Commercial links should be identifiable and governed by our <TrustLink href="/affiliate-disclosure">Affiliate Disclosure</TrustLink>.</p> },
    { id: "sources", title: "Sources and statistics", content: <p>We use structured football-data providers and information stored for the relevant fixture, competition and teams. Time-sensitive claims should be tied to available data and its freshness. We do not present a failed or unavailable feed as proof that no injuries, suspensions or other events exist.</p> },
    { id: "prediction-standards", title: "Prediction standards", content: <ul><li>Use evidence relevant to the fixture and recommended market.</li><li>Distinguish facts, estimates and analytical opinion.</li><li>Avoid fabricated statistics, team news, quotations or sources.</li><li>Use confidence consistently and never as a promise.</li><li>Acknowledge material uncertainty and contradictory signals.</li><li>Keep a settled record rather than quietly removing unsuccessful published picks.</li></ul> },
    { id: "prohibited", title: "Prohibited claims", content: <><PolicyCallout tone="warning">BetGenius must not describe an uncertain outcome as guaranteed, certain, fixed, risk-free, a sure win or 100% accurate, or use near-certainty wording that creates the same impression.</PolicyCallout><p>We also do not describe betting as reliable income, an investment or a way to recover losses.</p></> },
    { id: "updates", title: "Updates and corrections", content: <p>Upcoming-fixture information may be updated when material facts change. Clear factual errors should be corrected promptly once verified. A correction should not rewrite the historical outcome of a published pick or disguise its settlement. Where a material change affects meaning, the page should make the update understandable.</p> },
    { id: "report", title: "How to report an error", content: <p>Use the verified channel on our <TrustLink href="/contact">Contact page</TrustLink>. Include the page URL, the exact statement or data point, why it appears wrong and a reliable supporting source if available. We review good-faith reports; disagreement with a prediction alone is not evidence of a factual error.</p> },
    { id: "conflicts", title: "Conflicts of interest", content: <p>Contributors and decision-makers should disclose material commercial or personal interests relevant to content. Where a conflict cannot be managed transparently, the person concerned should not control the analytical conclusion.</p> },
    { id: "responsibility", title: "Responsible gambling", content: <p>Risk information should be visible and proportionate to the content. We do not target minors or encourage chasing losses, borrowing or unaffordable stakes. See our <TrustLink href="/responsible-gambling">Responsible Gambling</TrustLink> guidance.</p> },
  ]} />;
}
