/**
 * Real replay for the confidence-as-second-signal rule.
 *
 * Targets exactly the population the rule is aimed at: rows the live prompt
 * produced as a SIDE HEDGE at or above HEDGE_CONFIDENCE_REVIEW_THRESHOLD. The
 * stored row is the "before" — it was generated by the deployed prompt — and
 * the replay runs the same stored digest through the new one, so the digest is
 * byte-identical and the prompt is the only variable.
 *
 * A control group replays LOW-confidence hedges. If the rule is working as a
 * consistency check rather than a quota, those should mostly stay hedges: the
 * point is not to manufacture MATCH_WINNER picks.
 *
 * PACING: each generation costs 6-8k tokens and the Groq fallback is capped at
 * 8000 tokens/minute, so calls are spaced by --delay seconds (default 70). An
 * unpaced run returns mostly 429s and is not evidence of anything.
 *
 * Run: npx tsx scripts/replay-confidence-consistency.ts [perGroup] [--delay=70]
 */
export {};

const react = require("react");
react.cache = (fn: any) => fn;

const SIDE_HEDGES = ["DOUBLE_CHANCE", "DRAW_NO_BET", "WIN_EITHER_HALF"];

async function main() {
  const { prisma } = await import("../src/lib/prisma");
  const { generatePredictionForFixture, HEDGE_CONFIDENCE_REVIEW_THRESHOLD } = await import("../src/lib/ai/analysis");
  const { parseStoredContext } = await import("../src/lib/ai/context");
  const { resolveGenerationRisk } = await import("../src/lib/ai/generationRisk");
  const { deriveMarketAndPick, isValidSelection } = await import("../src/lib/markets");

  const perGroup = Number(process.argv[2] ?? 8);
  const delayMs = Number((process.argv.find((a) => a.startsWith("--delay=")) ?? "--delay=70").split("=")[1]) * 1000;
  for (let i = 0; i < 5; i++) { try { await prisma.$queryRaw`SELECT 1`; break; } catch { await new Promise((r) => setTimeout(r, 3000)); } }

  const rows = await prisma.prediction.findMany({
    where: { aiJobId: { not: null }, marketType: { in: SIDE_HEDGES }, homeTeam: { not: null } },
    select: {
      homeTeam: true, awayTeam: true, leagueName: true, leagueApiId: true,
      marketType: true, pick: true, confidence: true,
      aiJob: { select: { context: true, prompt: true } },
    },
    orderBy: { createdAt: "desc" },
    take: 400,
  });

  const withDigest = rows.filter((r) => parseStoredContext(r.aiJob?.context));
  const seen = new Set<string>();
  const dedupe = (rs: typeof withDigest) => rs.filter((r) => {
    const k = `${r.homeTeam}|${r.awayTeam}`;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  const target = dedupe(withDigest.filter((r) => r.confidence >= HEDGE_CONFIDENCE_REVIEW_THRESHOLD)).slice(0, perGroup);
  const control = dedupe(withDigest.filter((r) => r.confidence <= 72)).slice(0, perGroup);

  const run = async (label: string, group: typeof target) => {
    console.log(`\n===== ${label} (n=${group.length}) =====`);
    let toWinner = 0, keptHedgeLower = 0, keptHedgeSame = 0, other = 0;
    for (const [idx, row] of group.entries()) {
      if (idx > 0) await new Promise((r) => setTimeout(r, delayMs));
      const digest = parseStoredContext(row.aiJob!.context)!;
      let categories: string[] = [];
      try { categories = JSON.parse(row.aiJob!.prompt)?.categories ?? []; } catch {}
      const route = resolveGenerationRisk(categories, row.leagueApiId);
      try {
        const result = await generatePredictionForFixture({ digest, tiers: route.promptTiers, riskCalibration: "margin" });
        const p = (result.output.predictions ?? [])[0];
        if (!p) { console.log(`  ${row.homeTeam} v ${row.awayTeam} — no prediction returned`); continue; }
        const ok = isValidSelection(p.marketType, p.selection);
        const text = ok
          ? deriveMarketAndPick(p.marketType, p.selection, row.homeTeam!, row.awayTeam!, { market: p.marketType, pick: "" }).pick
          : "(invalid)";
        const nowConf = Math.round(p.confidence);
        let verdict: string;
        if (p.marketType === "MATCH_WINNER") { toWinner++; verdict = "-> MATCH_WINNER"; }
        else if (SIDE_HEDGES.includes(p.marketType) && nowConf < row.confidence) { keptHedgeLower++; verdict = "-> hedge kept, confidence LOWERED"; }
        else if (SIDE_HEDGES.includes(p.marketType)) { keptHedgeSame++; verdict = "-> hedge kept, confidence held"; }
        else { other++; verdict = "-> other market"; }
        console.log(`  ${row.homeTeam} v ${row.awayTeam} [${row.leagueName}]`);
        console.log(`     was: ${row.marketType} ${row.pick} @ ${row.confidence}%`);
        console.log(`     now: ${p.marketType} ${text} @ ${nowConf}%   ${verdict}`);
      } catch (err: any) {
        console.log(`  ${row.homeTeam} v ${row.awayTeam} — failed: ${err?.message ?? err}`);
      }
    }
    console.log(`  --- switched to MATCH_WINNER: ${toWinner} | hedge kept w/ lower confidence: ${keptHedgeLower} | hedge unchanged: ${keptHedgeSame} | other: ${other}`);
    return { toWinner, keptHedgeLower, keptHedgeSame, other };
  };

  console.log(`threshold under test: ${HEDGE_CONFIDENCE_REVIEW_THRESHOLD}`);
  const t = await run(`TARGET — side hedges stored at >= ${HEDGE_CONFIDENCE_REVIEW_THRESHOLD}`, target);
  const c = await run("CONTROL — side hedges stored at <= 72 (should mostly stay hedges)", control);

  console.log("\n===== SUMMARY =====");
  console.log(`  target : ${t.toWinner}/${target.length} became MATCH_WINNER, ${t.keptHedgeLower} kept the hedge at a lower number`);
  console.log(`  control: ${c.toWinner}/${control.length} became MATCH_WINNER (a high number here would mean forced rotation, not a consistency check)`);

  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
